language: node_js
node_js:
  - "10.15.3"

install:
  - npm install
  - npm install --only=dev
  - npm install client
  - cd client
  - npm install --only=dev

script:
  - cd client
  - pwd
  - npm run test